"""model_table

Revision ID: 1848b2f05949
Revises: 9b2691fa26f4
Create Date: 2020-06-17 01:40:15.580174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1848b2f05949'
down_revision = '9b2691fa26f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('Model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=80), nullable=False),
    sa.Column('Logo', sa.BLOB(), nullable=True),
    sa.Column('Product picture', sa.BLOB(), nullable=True),
    sa.Column('Description', sa.String(length=500), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['Category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Name')
    )
    op.drop_table('Item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('Logo', sa.BLOB(), nullable=True),
    sa.Column('Product picture', sa.BLOB(), nullable=True),
    sa.Column('Description', sa.VARCHAR(length=500), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Name')
    )
    op.drop_table('Model')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
