"""category_image_added

Revision ID: 1c82ae10d083
Revises: 4429a94265cd
Create Date: 2020-07-28 12:32:40.348796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c82ae10d083'
down_revision = '4429a94265cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Category', sa.Column('Image', sa.Unicode(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Category', 'Image')
    # ### end Alembic commands ###
