"""model_characteristics_added

Revision ID: 4db2c98dc94d
Revises: 5daf25e84504
Create Date: 2020-07-30 15:04:49.242069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4db2c98dc94d'
down_revision = '5daf25e84504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Model', sa.Column('Characteristics', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('Model', sa.Column('Characteristics RU', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('Model', sa.Column('Characteristics UK', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Model', 'Characteristics UK')
    op.drop_column('Model', 'Characteristics RU')
    op.drop_column('Model', 'Characteristics')
    # ### end Alembic commands ###
