"""Localisation_models

Revision ID: 55bf43952107
Revises: cdd6d9c988f1
Create Date: 2020-07-07 21:02:14.847192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55bf43952107'
down_revision = 'cdd6d9c988f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Brand', sa.Column('Country RU', sa.String(length=100), nullable=True))
    op.add_column('Brand', sa.Column('Country UK', sa.String(length=100), nullable=True))
    op.add_column('Brand', sa.Column('Name RU', sa.String(length=100), nullable=True))
    op.add_column('Brand', sa.Column('Name UK', sa.String(length=100), nullable=True))
    op.add_column('Catalog', sa.Column('Name RU', sa.String(length=80), nullable=True))
    op.add_column('Catalog', sa.Column('Name UK', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'Catalog', ['Name UK'])
    op.create_unique_constraint(None, 'Catalog', ['Name RU'])
    op.add_column('Category', sa.Column('Name RU', sa.String(length=80), nullable=True))
    op.add_column('Category', sa.Column('Name UK', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'Category', ['Name RU'])
    op.create_unique_constraint(None, 'Category', ['Name UK'])
    op.add_column('Job', sa.Column('Conditions RU', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Job', sa.Column('Conditions UK', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Job', sa.Column('Position RU', sa.String(length=500), nullable=True))
    op.add_column('Job', sa.Column('Position UK', sa.String(length=500), nullable=True))
    op.add_column('Job', sa.Column('Requirements RU', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Job', sa.Column('Requirements UK', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Job', sa.Column('Responsibilities RU', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Job', sa.Column('Responsibilities UK', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Model', sa.Column('Description RU', sa.TEXT(), nullable=True))
    op.add_column('Model', sa.Column('Description UK', sa.TEXT(), nullable=True))
    op.add_column('Model', sa.Column('Name RU', sa.String(length=80), nullable=True))
    op.add_column('Model', sa.Column('Name UK', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'Model', ['Name RU'])
    op.create_unique_constraint(None, 'Model', ['Name UK'])
    op.add_column('ReagentSubsection', sa.Column('Name RU', sa.String(length=80), nullable=True))
    op.add_column('ReagentSubsection', sa.Column('Name Uk', sa.String(length=80), nullable=True))
    op.add_column('Service', sa.Column('Text RU', sa.TEXT(), nullable=True))
    op.add_column('Service', sa.Column('Text UK', sa.TEXT(), nullable=True))
    op.add_column('Service', sa.Column('Title RU', sa.String(length=400), nullable=True))
    op.add_column('Service', sa.Column('Title UK', sa.String(length=400), nullable=True))
    op.add_column('Slider', sa.Column('Text RU', sa.TEXT(), nullable=True))
    op.add_column('Slider', sa.Column('Text UK', sa.TEXT(), nullable=True))
    op.add_column('Slider', sa.Column('Title RU', sa.String(length=80), nullable=True))
    op.add_column('Slider', sa.Column('Title UK', sa.String(length=80), nullable=True))
    op.add_column('reagent', sa.Column('Method RU', sa.String(length=200), nullable=True))
    op.add_column('reagent', sa.Column('Method Uk', sa.String(length=200), nullable=True))
    op.add_column('reagent', sa.Column('Name RU', sa.String(length=80), nullable=True))
    op.add_column('reagent', sa.Column('Name Uk', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'reagent', ['Method Uk'])
    op.create_unique_constraint(None, 'reagent', ['Method RU'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reagent', type_='unique')
    op.drop_constraint(None, 'reagent', type_='unique')
    op.drop_column('reagent', 'Name Uk')
    op.drop_column('reagent', 'Name RU')
    op.drop_column('reagent', 'Method Uk')
    op.drop_column('reagent', 'Method RU')
    op.drop_column('Slider', 'Title UK')
    op.drop_column('Slider', 'Title RU')
    op.drop_column('Slider', 'Text UK')
    op.drop_column('Slider', 'Text RU')
    op.drop_column('Service', 'Title UK')
    op.drop_column('Service', 'Title RU')
    op.drop_column('Service', 'Text UK')
    op.drop_column('Service', 'Text RU')
    op.drop_column('ReagentSubsection', 'Name Uk')
    op.drop_column('ReagentSubsection', 'Name RU')
    op.drop_constraint(None, 'Model', type_='unique')
    op.drop_constraint(None, 'Model', type_='unique')
    op.drop_column('Model', 'Name UK')
    op.drop_column('Model', 'Name RU')
    op.drop_column('Model', 'Description UK')
    op.drop_column('Model', 'Description RU')
    op.drop_column('Job', 'Responsibilities UK')
    op.drop_column('Job', 'Responsibilities RU')
    op.drop_column('Job', 'Requirements UK')
    op.drop_column('Job', 'Requirements RU')
    op.drop_column('Job', 'Position UK')
    op.drop_column('Job', 'Position RU')
    op.drop_column('Job', 'Conditions UK')
    op.drop_column('Job', 'Conditions RU')
    op.drop_constraint(None, 'Category', type_='unique')
    op.drop_constraint(None, 'Category', type_='unique')
    op.drop_column('Category', 'Name UK')
    op.drop_column('Category', 'Name RU')
    op.drop_constraint(None, 'Catalog', type_='unique')
    op.drop_constraint(None, 'Catalog', type_='unique')
    op.drop_column('Catalog', 'Name UK')
    op.drop_column('Catalog', 'Name RU')
    op.drop_column('Brand', 'Name UK')
    op.drop_column('Brand', 'Name RU')
    op.drop_column('Brand', 'Country UK')
    op.drop_column('Brand', 'Country RU')
    # ### end Alembic commands ###
