"""reagent_descritption_added

Revision ID: 59d0a7411262
Revises: a53d6a83a1a2
Create Date: 2020-07-31 13:08:56.921568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59d0a7411262'
down_revision = 'a53d6a83a1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reagent', sa.Column('Description', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('reagent', sa.Column('Description RU', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('reagent', sa.Column('Description UK', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reagent', 'Description UK')
    op.drop_column('reagent', 'Description RU')
    op.drop_column('reagent', 'Description')
    # ### end Alembic commands ###
