"""catalog_image_added

Revision ID: 5daf25e84504
Revises: 34a0d673b54b
Create Date: 2020-07-29 12:26:17.752870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5daf25e84504'
down_revision = '34a0d673b54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Catalog', sa.Column('Image', sa.Unicode(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Catalog', 'Image')
    # ### end Alembic commands ###
