"""item_table

Revision ID: 7d825fd1ef1d
Revises: 9b2691fa26f4
Create Date: 2020-06-16 23:19:52.877424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d825fd1ef1d'
down_revision = '9b2691fa26f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=80), nullable=False),
    sa.Column('Logo', sa.BLOB(), nullable=True),
    sa.Column('Product picture', sa.BLOB(), nullable=True),
    sa.Column('Description', sa.String(length=500), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Name')
    )
    op.alter_column('Category', 'catalog_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Category', 'catalog_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('Item')
    # ### end Alembic commands ###
