"""reviews_for_model_added

Revision ID: a53d6a83a1a2
Revises: 4db2c98dc94d
Create Date: 2020-07-30 18:05:09.744880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53d6a83a1a2'
down_revision = '4db2c98dc94d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('Review author', sa.String(length=40), nullable=False),
    sa.Column('Review text', sa.String(length=600), nullable=False),
    sa.Column('Review date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['Model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
