"""brand_model

Revision ID: a9eeccc7a4a0
Revises: c792a51d60d0
Create Date: 2020-07-23 16:23:51.283403

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a9eeccc7a4a0'
down_revision = 'c792a51d60d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Brand', sa.Column('Description', sa.TEXT(), nullable=True))
    op.add_column('Brand', sa.Column('Description RU', sa.TEXT(), nullable=True))
    op.add_column('Brand', sa.Column('Description UK', sa.TEXT(), nullable=True))
    op.add_column('Brand', sa.Column('Short description', sa.String(length=200), nullable=True))
    op.add_column('Brand', sa.Column('Short description RU', sa.String(length=200), nullable=True))
    op.add_column('Brand', sa.Column('Short description UK', sa.String(length=200), nullable=True))
    op.add_column('Model', sa.Column('Video link', sqlalchemy_utils.types.URLType, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Model', 'Video link')
    op.drop_column('Brand', 'Short description UK')
    op.drop_column('Brand', 'Short description RU')
    op.drop_column('Brand', 'Short description')
    op.drop_column('Brand', 'Description UK')
    op.drop_column('Brand', 'Description RU')
    op.drop_column('Brand', 'Description')
    # ### end Alembic commands ###
