"""product_models_table

Revision ID: 4733f6bcbdef
Revises:
Create Date: 2020-06-21 12:57:32.536284

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '4733f6bcbdef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Country', sa.String(length=100), nullable=False),
    sa.Column('Brand website', sa.Unicode(length=128), nullable=True),
    sa.Column('Logo', sa.Unicode(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('Job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Position', sa.String(length=500), nullable=False),
    sa.Column('Requirements', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('Responsibilities', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('Conditions', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ReagentSubsection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('Service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=400), nullable=False),
    sa.Column('Icon', sa.String(length=150), nullable=False),
    sa.Column('Text', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Slider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Background', sa.Unicode(length=128), nullable=False),
    sa.Column('Title', sa.String(length=80), nullable=False),
    sa.Column('Text', sa.TEXT(), nullable=False),
    sa.Column('Link', sa.Unicode(length=128), nullable=True),
    sa.Column('slide_order_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Text'),
    sa.UniqueConstraint('Title')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('Category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=80), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['Catalog.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('reagent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subsection_id', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=80), nullable=False),
    sa.Column('Method', sa.String(length=200), nullable=False),
    sa.Column('DistributionCode', sa.dialects.postgresql.JSON, nullable=False),
    sa.ForeignKeyConstraint(['subsection_id'], ['ReagentSubsection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Method'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('Model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=80), nullable=False),
    sa.Column('Logo', sa.Unicode(length=128), nullable=True),
    sa.Column('Product picture',sa.ARRAY(sa.Unicode(length=128)), nullable=True),
    sa.Column('Description', sa.TEXT(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['Category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Model')
    op.drop_table('reagent')
    op.drop_table('Category')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('Slider')
    op.drop_table('Service')
    op.drop_table('ReagentSubsection')
    op.drop_table('Job')
    op.drop_table('Catalog')
    op.drop_table('Brand')
    # ### end Alembic commands ###
