"""news_tables

Revision ID: cdd6d9c988f1
Revises: 4733f6bcbdef
Create Date: 2020-06-21 15:09:35.333124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd6d9c988f1'
down_revision = '4733f6bcbdef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NewsCategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('NewsOn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('Title', sa.String(length=80), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('preview_image', sa.Unicode(length=128), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('Images', sa.ARRAY(sa.Unicode(length=128)), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['NewsCategory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NewsOn')
    op.drop_table('NewsCategory')
    # ### end Alembic commands ###
